### ISSUE TITLE
Scrolling broken inside Flex

### ISSUE THREAD

**Issue by rhzk** [linebender/druid#1150] opened 2020-08-22 04:20 UTC
If Scroll is placed inside a Flex::column it does not work at all, and if it is placed inside a Flex::row it works but the bar is drawn on top of the children.

How to reproduce:
```
    Flex::column().with_child( // OR Row
        Scroll::new(Flex::column()
            .with_child(Label::new("1"))
            .with_child(Label::new("2"))
            .with_child(Label::new("3"))
            .with_child(Label::new("4"))
            .with_child(Label::new("5"))
            .with_child(Label::new("6"))
            .with_child(Label::new("7"))
            .with_child(Label::new("8"))
            .with_child(Label::new("9"))))
```

**Comment by ForLoveOfCats** [comment] 2020-08-23 19:58
That's along the lines of the logic I was thinking, thanks for clarifying the situation. There actually is a warning for non-flex children having infinite size on either axis but it doesn't seem to be triggering so I'm going to take a look into that.

I suppose this is another case of the difference between flex and non-flex children being less obvious than we would like and how `add_child` seems like the "default" option like in https://github.com/linebender/druid/issues/1130

**Comment by cmyr** [comment] 2020-08-26 18:43
Oops, I misunderstood the problem I think.

In the example posted, no scroll is happening because the scroll widget isn't constrained on its primary axis; it is measuring all of its children, and then returning this size to the flex. The flex will let a non-flex child  overflow on the primary axis without complaint.

If you want to force it to scroll, you can give the scroll widget a fixed height.

**Comment by ForLoveOfCats** [comment] 2020-08-26 20:59
Yes that was determined to the the issue hence why I suggested that this is another example of possible confusion surrounding flex and non-flex children even by those of us who should know better.

**Comment by ForLoveOfCats** [comment] 2020-09-07 02:11
Because this is expected behavior I'm going to close this. The discussion about the API to interact with Flex and the potential for confusion is being tracked over at https://github.com/linebender/druid/issues/1130

**Closed by ForLoveOfCats** 2020-09-07 02:11 UTC
Labels: question, widget
