### ISSUE TITLE
Text based widgets panic if font size is [-∞ , 0]

### ISSUE THREAD

**Issue by rhzk** [linebender/druid#1156] opened 2020-08-24 12:16 UTC
Currently Label and Textbox will panic if text size is between [-∞ , 0]

Steps to reproduce:
```
Label::new("").with_text_size(0.0)
// OR
EnvScope::new(|env, data| {
    env.set(theme::TEXT_SIZE_NORMAL, 0.0);
}, TextBox::new())
```
Positive values does not seem to cause a panic, even 0.000000001

Maybe this issue should be in Piet?

**Comment by ForLoveOfCats** [comment] 2020-08-25 01:21
What platform are you on?

CC @cmyr

**Comment by rhzk** [comment] 2020-08-25 21:48
Windows

**Comment by derekdreery** [comment] 2020-08-25 22:17
What is the expected behavior for negative font size?

**Comment by ForLoveOfCats** [comment] 2020-08-25 23:21
That's a good point

I just checked on the GTK shell and it doesn't panic there, in fact negative font sizes cause the text to paint with abs(size) but upside down. We should probably have a panic with a sane error message on all platforms if the font size is < 1 or some other reasonable minimum value. We might already be outputting a useful panic message on Windows, I can't test it atm.

**Comment by cmyr** [comment] 2020-08-26 17:32
Good issue, thanks, will look at this in piet. I think we should at least `ceil(font_size, 0.0)`, although a debug panic also seems reasonable.

**Comment by cmyr** [comment] 2020-08-26 18:07
Also doesn't crash on mac, which does something like `if size <= 0.0 {  size = 12.0 }`.

Overall I like this solution of using the default size if an invalid size is provided, and would suggest adopting that unless someone has a better idea.

**Comment by cmyr** [comment] 2020-08-26 18:23
@rhzk can you reproduce this issue on master? I'm not able to reproduce it in the latest piet, which we're now using.

**Comment by ForLoveOfCats** [comment] 2020-08-26 20:55
If a size of 0 is conceivably valid (which one of your comments implies) it could be represented by an unsigned value thus encoding this limit at the type level.

**Comment by cmyr** [comment] 2020-08-26 21:04
Unfortunately there are no unsigned floats, and we want font size to be a float, by convention. 😒

**Comment by ForLoveOfCats** [comment] 2020-08-26 21:49
Ahhhhhhh, duh :facepalm: I didn't even think about non-integer sizes

**Comment by rhzk** [comment] 2020-08-26 22:08
Seems to be fixed on master, no longer crashes. If the text is <= 0.0 it creates it with a bigger size (12 or something). 
If its 0.1 I cant see the text so I guess it tries to draw it with that size. 
Should there be a min size cap and numbers below that set to the cap, or maybe <= 0.0 should not draw any text.

I have wondered why rust doesnt have unsigned floats, it would be useful when you want to guarantee a positive value and have precision

**Comment by cmyr** [comment] 2020-08-26 22:55
yea, this behaviour should be standardized; it seems like both mac and windows use `12.0` if the passed value is <= 0, and I think we should just enforce that.

**Comment by cmyr** [comment] 2020-08-26 22:57
Opened an issue in piet to track this; as the crash is fixed I'll close this.

**Closed by cmyr** 2020-08-26 22:57 UTC
Labels: crash, shell
