### ISSUE TITLE
TextBox doesn't reset position after unfocused

### ISSUE THREAD

**Issue by MGlolenstine** [linebender/druid#1125] opened 2020-08-11 13:41 UTC
Within the same example from #1124 I've found yet another problem.

If we type more text than there's space for in the first `TextBox`, the text starts shifting. If we switch to another `TextBox` and start deleting from the beginning, the weird shift starts showing.
![image](https://user-images.githubusercontent.com/9406770/89904308-0bcbf400-dbe9-11ea-84a9-26c45e162eb1.png)
In my opinion the text's position should reset when unfocused, at least that's how most of the other applications do it.

# EDIT:
This is what happens, when there's no text and only hints remain.
![image](https://user-images.githubusercontent.com/9406770/89904710-8e54b380-dbe9-11ea-9b12-c710668bfe3e.png)

**Comment by cmyr** [comment] 2020-08-17 20:11
Thanks, will keep an eye open for this when I start redoing text stuff in druid (shortly)

**Comment by MGlolenstine** [comment] 2020-08-17 21:15
> Thanks, will keep an eye open for this when I start redoing text stuff in druid (shortly)

You're welcome and thanks for working on it 😉

**Comment by cmyr** [comment] 2020-08-26 20:20
I think this is really a dupe of your previous issue? As in this describes the problem, and the other issue is capturing aa symptom of that. I would close one of them, maybe the other one?

**Comment by MGlolenstine** [comment] 2020-08-26 20:23
I wouldn't say it's a dupe, as they describe two different problems, which are both connected to TextBoxes.
If you want to close any of them, feel free to do so.
If I had a say, I'd leave the first one, as it has a MinimalRunnableExample attached.

**Comment by cmyr** [comment] 2020-08-26 20:42
I think they describe different manifestations of the same problem? If a textbox deselects its contents when it loses focus, (this issue) then that fixes the problem of multiple textboxes having selections simultaneously?

**Comment by MGlolenstine** [comment] 2020-08-26 20:49
You are indeed correct.

**Closed** 2021-03-29 19:41 UTC
Labels: bug, widget
