### ISSUE TITLE
text alignment is broken

### ISSUE THREAD

**Issue by sysint64** [linebender/druid#1180] opened 2020-09-04 04:35 UTC
In the master branch, the label widget and the button widget text aren't centered.

![image](https://user-images.githubusercontent.com/1782848/92199813-55cf8f00-eea2-11ea-8f2d-349a8522d0bc.png)

**Comment by Finnerale** [comment] 2020-09-04 06:44
Hmm, I don't see this with GTK. What system are you using?

**Comment by sysint64** [comment] 2020-09-04 06:48
Manjaro xfce

**Comment by Finnerale** [comment] 2020-09-04 06:57
I'm running Arch with Gnome, so we should have a very similar setup...
Have you tried `cargo clean`? Maybe that fixes something. Also, what code are you running exactly? Does this happen with the examples?

**Comment by sysint64** [comment] 2020-09-04 07:55
Tried, the same. I'm running the flex example.

**Comment by sysint64** [comment] 2020-09-04 07:58
When I use druid `v0.6.0`, it looks fine, but in the master branch I have the issue.

**Comment by Finnerale** [comment] 2020-09-04 08:02
Are you using High-DPI Scaling or something like this? Because I can't reproduce it.

**Comment by sysint64** [comment] 2020-09-04 09:46
> Are you using High-DPI Scaling or something like this?

No, I'll check on a different computer later.

**Comment by sysint64** [comment] 2020-09-05 05:00
On my MacBook it looks fine, but text in the textbox isn't centered.
<img width="167" alt="Screenshot 2020-09-05 at 12 00 05" src="https://user-images.githubusercontent.com/1782848/92298051-584bea80-ef6f-11ea-8db6-54f29ca2d3b0.png">

**Comment by sysint64** [comment] 2020-09-05 05:07
Version 0.6.0 on mac book:
<img width="172" alt="Screenshot 2020-09-05 at 12 07 18" src="https://user-images.githubusercontent.com/1782848/92298160-5afb0f80-ef70-11ea-8fd7-d7daac11ced2.png">

**Comment by Finnerale** [comment] 2020-09-05 16:55
Hmm, no idea what's going on...

This is what it looks like for me:
![asdasdas](https://user-images.githubusercontent.com/10746692/92309836-235c8980-efa9-11ea-8f2b-990a1e7346a5.png)
(Seems to match what you see on your MacBook)

Maybe @cmyr has an idea / is aware of this?

**Comment by cmyr** [comment] 2020-09-06 16:06
oh yea this is a known issue and one of the things that got my digging back into text. baseline alignment is tricky, and we don't have any mechanism for it, although I have a patch working locally. Will depend on getting #1182 landed.

**Comment by cmyr** [comment] 2020-10-21 17:41
This should now be fixed, although you will need to specifically set the `Flex` to use `CrossAxisAlignment::Baseline`.

**Closed by cmyr** 2020-10-21 17:41 UTC
Labels: bug, widget
