### ISSUE TITLE
[panic] No available pixel format

### ISSUE THREAD

**Issue by merspir** [linebender/druid#2266] opened 2022-09-29 06:30 UTC
Hello, 
I'm using Windows 10 on a VMware Horizon virtual desktop, that I access through VMware Horizon Client.
I downloaded the Lapce text editor 0.2.0 (portable), which uses a [fork of Druid](https://github.com/lapce/druid) for its UI.
That repo doesn't have an Issues tab, so I'd thought I'd open an issue here, in case it might be relevant to other projects that use Druid.

Lapce panics at start with the following error:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(no available pixel format)'

And mentions druid-shell/src/backend/windows/window.rs:843:26

Screenshot:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/102377538/192954790-8307a3de-358d-45fe-9f05-161f1cad8610.png">

**Comment by xStrom** [comment] 2022-12-04 16:31
Based on discussion in the Lapce issues this seems to be related to their modified GPU code. Thus I'm going to close this as not applicable. If you can reproduce the crash with any of the Druid examples we can reopen it.

**Closed by xStrom** 2022-12-04 16:31 UTC
