### ISSUE TITLE
issue using druid::im::{Vector}

### ISSUE THREAD

**Issue by bwintertkb** [linebender/druid#2137] opened 2022-02-04 18:29 UTC
Hi guys,

I'm pretty new to rust and I've been spending some time looking at the UI options out there. This one is awesome!

I have an issue though using the druid immutable vector. I can't seem to import it.

It doesn't work if my dependency is druid = "0.7" or the repo link. 

Do you guys know how to import it? Currently going through your example files.

**Comment by Maan2003** [comment] 2022-02-04 19:23
duplicate of #2080

**Comment by bwintertkb** [comment] 2022-02-04 19:56
> duplicate of #2080

legend

**Closed** 2022-02-24 07:53 UTC
