### ISSUE TITLE
Hide/Disable widgets or buttons from state

### ISSUE THREAD

**Issue by chrisheib** [linebender/druid#1694] opened 2021-04-03 21:08 UTC
Hey, I have a widget for a song, which is:

![grafik](https://user-images.githubusercontent.com/6112968/113491375-96db6080-94d0-11eb-9743-87fd35f3254e.png)

On clicking on the 'x' I want some stuff to happen, and a function to set a field of the song 'x_pressed' to be set to true, and the x-button to disappear or get deactivated. Is there a widget with this functionality available? It would surprise me if I was the first one wanting to use this.

Code now:

```
    let skip = Button::new("✘")
        .on_click(|_: &mut EventCtx, song: &mut SongData, _: &Env| song.skip = true);
```

I want:

```
    let skip = Button::new("✘")
        .on_click(|_: &mut EventCtx, song: &mut SongData, _: &Env| {song.skip = true; song.x_pressed = true;})
        .enabled(|_: &mut EventCtx, song: &mut SongData, _: &Env| !song.x_pressed);
```

**Comment by HoNile** [comment] 2021-04-04 09:30
Hello, disable widgets are in progress see #1632, if you want to hide a button it should be possible with a `ViewSwitcher` on the `Button` and an `SizedBox` (cf. example view_switcher).

**Comment by chrisheib** [comment] 2021-04-04 11:52
@HoNile thanks alot, using the viewswitcher works nicely for the time being!

```
    let skip_panel = ViewSwitcher::new(
        |data: &SongData, _env| data.is_last,
        |selector, _data, _env| match selector {
            false => Box::new(
                Button::new("✘")
                    .on_click(|_: &mut EventCtx, song: &mut SongData, _: &Env| song.skip = true),
            ),
            true => Box::new(Flex::column()),
        },
    );
```

**Comment by SecondFlight** [comment] 2021-04-05 14:25
Closing as a duplicate of #746.

**Closed by SecondFlight** 2021-04-05 14:25 UTC

**Comment by xarvic** [comment] 2021-04-11 21:46
@chrisheib the disabled state is merged, a disabled_if WidgetExt method is on the way (#1702).
