### ISSUE TITLE
Widgets leak the container (in the flex example)

### ISSUE THREAD

**Issue by kud1ing** [linebender/druid#1773] opened 2021-05-11 14:55 UTC
<img width="732" alt="Bildschirmfoto 2021-05-11 um 20 10 49" src="https://user-images.githubusercontent.com/391975/117864418-10ffc180-b295-11eb-8b39-6334874b3b1d.png">

**Comment by cmyr** [comment] 2021-06-28 17:50
We overflow by default when we can't satisfy a layout. It might make sense for the textbox to have a default max width, though?

**Comment by kud1ing** [comment] 2021-06-29 06:21
Not sure. I would expect:
* either the box and the window to grow as the text does
* or the sized of the things to be static and the text be truncated e.g. similar to in CSS with ellipsis: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by cmyr** [comment] 2021-06-29 13:39
By design, piet does not support text truncation, because it was going to be a hassle to come up with an API that we could implement reasonably well across the various platforms. The decision was that piet would just lay out the text in the provided space, and then handling overflow would be a job for the next level up in the stack.

There is some hacky support for the window to be sized based on content, but that was not originally part of the design of the layout system, and doesn't really solve the problem in a general sense; eventually your window is the size of your screen, and then you'd have a decision to make.

My personal instinct on this is that the druid user, when designing their layout, should be aware of situations where arbitrary text might be displayed, and account for this. In the context of a `TextBox`, this would mean providing some size constraints. By default, a single-line textbox will size itself to the size of the text, and if you want it to start scrolling before then you'll need to provide it with an explicit width. In the context of a label, there is a provided `LineBreaking` enum that lets you specify behaviour on horizontal overflow: clipping, wrapping, or overflowing.

A proper truncation API will be a goal for the next iteration of our text API, but that's out of scope for a while.

**Comment by kud1ing** [comment] 2021-06-29 14:33
Thank you for the thorough explanation.
Do you see anything actionable in this issue?

**Comment by cmyr** [comment] 2021-06-29 17:22
Only possible that this should be better documented? 🎭 In any case I'll close, sorry again for the slow response.

**Closed by cmyr** 2021-06-29 17:22 UTC
Labels: layout
