### ISSUE TITLE
Transparent windows

### ISSUE THREAD

**Issue by Maan2003** [linebender/druid#1117] opened 2020-08-06 12:55 UTC
I am not sure about other platforms but windows supports transparent window with `SetLayeredWindowAttributes` function

**Comment by djeedai** [comment] 2021-01-04 16:25
@Finnerale / @cmyr / @raphlinus : This looks like a duplicate of #1249 no?

Also for reference see #1462 for some related but different issue.

**Comment by Finnerale** [comment] 2021-01-04 16:32
Yup, this should be closed in favor of #1249.

**Closed** 2021-01-04 16:33 UTC
Labels: duplicate, enhancement, shell
